tidy -config tidyconf.txt research_old\index.html > research\index.html
tidy -config tidyconf.txt research_old\node1.html > research\node1.html
tidy -config tidyconf.txt research_old\node2.html > research\node2.html
tidy -config tidyconf.txt research_old\node3.html > research\node3.html
tidy -config tidyconf.txt research_old\node4.html > research\node4.html
tidy -config tidyconf.txt research_old\node5.html > research\node5.html
tidy -config tidyconf.txt research_old\node6.html > research\node6.html
tidy -config tidyconf.txt research_old\node7.html > research\node7.html
tidy -config tidyconf.txt research_old\node8.html > research\node8.html
tidy -config tidyconf.txt research_old\node9.html > research\node9.html
tidy -config tidyconf.txt research_old\node10.html > research\node10.html
tidy -config tidyconf.txt research_old\node11.html > research\node11.html
tidy -config tidyconf.txt research_old\node12.html > research\node12.html
tidy -config tidyconf.txt research_old\node13.html > research\node13.html
tidy -config tidyconf.txt research_old\node14.html > research\node14.html
tidy -config tidyconf.txt research_old\node15.html > research\node15.html
tidy -config tidyconf.txt research_old\node16.html > research\node16.html
tidy -config tidyconf.txt research_old\s1node1.html > research\s1node1.html
tidy -config tidyconf.txt research_old\s1node2.html > research\s1node2.html
tidy -config tidyconf.txt research_old\s1node3.html > research\s1node3.html
tidy -config tidyconf.txt research_old\s2node1.html > research\s2node1.html
tidy -config tidyconf.txt research_old\s2node2.html > research\s2node2.html
tidy -config tidyconf.txt research_old\research.html > research\research.html
tidy -config tidyconf.txt research_old\sec1.html > research\sec1.html
tidy -config tidyconf.txt research_old\sec2.html > research\sec2.html